### PR TITLE
Add maximize-build-space action

### PR DESCRIPTION
**Pull request by JoshOrndorff**
inspired by cdaa8c7bb385ca42359d0071348b2a7805dc55d3

This PR adds this simple magical (hacky) github action which gets us enough extra disk space to build the massive polkadot crates.

### CODE REVIEW

**Comment by JoshOrndorff** [comment]
running `cargo clean && cargo nextest run --release && du -h` locally shows that my Tuxedo directory totals to 11G after all tests run. That seems like it should be good enough. Maybe even enough to fit in the 14GB that we have without the magic action.

Let's see what the disk usage is without the release flag.

**Comment by muraca** [comment]
The action did not solve the problem we had, cargo gets stuck on some windows crate.
Thanks for testing my intuition with `--release` and pointing out it was indeed a good solution.

**Comment by muraca** [comment]
The action did not solve the problem we had, cargo gets stuck on some windows crate.
Thanks for testing my intuition with `--release` and pointing out it was indeed a good solution.

**Comment by JoshOrndorff** [comment]
> cargo gets stuck on some windows crate

How did you determine that. I can't see any logs from the failed jobs. (except for the first few steps which succeeded)

**Comment by muraca** [comment]
> > cargo gets stuck on some windows crate
> 
> How did you determine that. I can't see any logs from the failed jobs. (except for the first few steps which succeeded)

I ran the action and looked at the logs in real time for 30 minutes. I don't recommend doing it.

**Pull request closed without merging**
