### PR TITLE
Update substrate july 2023

### PR DESCRIPTION
**Pull request by JoshOrndorff**

### CODE REVIEW

**Comment by JoshOrndorff** [comment]
Ohh, oops, I didn't fix the tests yet.

**Comment by JoshOrndorff** [comment]
@muraca FYI This will conflict with #91 

Feel free to merge that one first since it is almost ready. Also feel free to take this one over if you want.

**Comment by muraca** [comment]
I think dependencies should be updated to whatever the latest release is, right? 
Looks like it is polkadot v1.1.0 on the new monorepo

**Comment by JoshOrndorff** [comment]
Indeed, we will need to update to even more recent stuff than the july 2023 release I originally mentioned. I'm fine with either doing it incrementally as several smaller PRs or all in one go.

**Pull request merged**
